# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddcf43813a81efccf3de72009f3144f09ca9ff8aa5b719ea6d5f79b10a26d5692e4caad034d48a9699562732a8a55820ffb230c4de38fe3f83d3cbdfa8fcde0d

test:
  secret_key_base: 0eeff44c45781e7d3651b11e0d4c1d6b83cd28200b1137803fc32a4053c8f8b7a22bd68ae92ea6cd89d98eaf55a086bc97721ae52f7fcede7d7b04b21a6b8bd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
